export const LOGIN_API = '/users/auth/login'
export const PROFILE_UPDATE_API = '/users/profile/update'
export const PROFILE_API = '/users/profile'
export const LIST_PRODUCTS_API = '/products'
export const PRODUCT_MASTER_DATA_API = '/products/master-data'
